model_name: "google/flan-t5-small"
train_file: "data/sample_lamini_docs_processed.jsonl"
output_dir: "outputs/flan-t5-small"
max_source_length: 512
max_target_length: 128
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 3e-4
num_train_epochs: 1
weight_decay: 0.01
warmup_ratio: 0.03
logging_steps: 50
save_steps: 200
evaluation_strategy: "no"
fp16: true
